server:
  port: 9090

login:
  authorization: false

my-log:
  src: ./log/

code-length: 4 #验证码长度



spring:
  rabbitmq:
    host: 120.55.80.133
    port: 5672
    username: jdfcc
    password: 1234
  #    publisherConfirmType: correlated #交换机开启发布确认模式
  #    publisherReturns: true #发布回退模式，若消息路由失败，回退给生产者
  application:
    name: Cang
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  redis:
    database: 1
    host: 120.55.80.133
    port: 6380
    password: 3039@Hyd123G,,,
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  # 邮件配置
  mail:
    # 邮件服务器地址
    host: smtp.qq.com
    # 你的邮箱地址
    username: 3039898075@qq.com
    # 授权码
    password: lyawhjywiwjudccf
    # 编码格式
    default-encoding: utf-8
    # 协议
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis-plus:
  type-aliases-package: com.Cang.entity # 别名扫描包

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名转换原则 TODO 开启驼峰命名有问题。

logging:
  level:
    com.Cang: debug
  pattern:
    dateformat: mm:ss.SSS

snowflake:
  data-center: 1 #数据中心id
  worker-id: 1 #机器id
