---
--- Generated by Luanalysis
--- Created by Jdfcc.
--- DateTime: 2023/8/7 15:33
---

local key=ARGV[1]
local key_prefix="CangRedisRetryLock:"
local lock=key_prefix+key

-- 加锁，成功则删除，失败则说明其他线程已开始对此key的删除操作
if(redis.call("SETNX",lock)) then
    -- 删除
    if(redis.call("EXISTS",key)) then
        redis.call("DEL",key)
        -- 删除成功
        return 1
    end
    redis.call("DEL",lock)
    -- key不存在,删除失败
    return 0
    -- 释放锁
end
-- 其他线程正在删除此key
return 2



