---
--- Generated by Luanalysis
--- Created by Jdfcc.
--- DateTime: 2023/1/26 17:19
---
local key=KEYS[1]
local threadId=ARGV[1]
local releaseTime=ARGV[2]
if(redis.call('exists', key)==0) then
    redis.call('hset', key,threadId,'1')
    redis.call('expire',key,releaseTime)
    return 1
end
if(redis.call('hexists',key==1)) then
    redis.call('hincrby',key,threadId,'1')
    redis.call('expire',key,releaseTime)
    return 1
end
return 0